name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          src-tauri/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    
    - name: Install npm dependencies
      run: npm install
      
    - name: Run tests
      run: npm run test:all
      
    - name: Build frontend
      run: npm run build
      
    - name: Build Tauri app (release)
      run: npm run build:release
    
    - name: Generate update manifest (Ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cat > latest.json << EOF
        {
          "version": "${{ github.ref_name }}",
          "notes": "See the assets to download this version and install.",
          "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "platforms": {
            "windows-x86_64": {
              "signature": "",
              "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/markdown-viewer_${{ github.ref_name }}_x64_en-US.msi.zip"
            },
            "darwin-x86_64": {
              "signature": "",
              "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/markdown-viewer_${{ github.ref_name }}_x64.dmg.tar.gz"
            },
            "linux-x86_64": {
              "signature": "",
              "url": "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/markdown-viewer_${{ github.ref_name }}_amd64.AppImage.tar.gz"
            }
          }
        }
        EOF
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src-tauri/target/release/bundle/msi/*.msi
          src-tauri/target/release/bundle/deb/*.deb
          src-tauri/target/release/bundle/rpm/*.rpm
          src-tauri/target/release/bundle/dmg/*.dmg
          src-tauri/target/release/bundle/appimage/*.AppImage
          latest.json
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}